import type { NextPage } from 'next'
import styled from 'styled-components'
import Head from 'next/head'

const Container = styled.div`
  padding: 0 32px;
`

const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 32px;
  text-align: center;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to Coinr
        </Title>
      </Main>
    </Container>
  )
}

export default Home
